version: '3'

tasks:
  check:
    internal: true
    desc: Verify integrity via script
    dir: ./
    cmds:
      - chmod +x ./scripts/verify_checksum.sh
      - ./scripts/verify_checksum.sh "{{.SOURCE}}" "{{.SHA}}"
